#!/usr/bin/env python3
"""Bake the agent skill into the binaries.

Reads every Markdown file under `.claude/skills/rocuronium` and writes one Swift file,
`EmbeddedSkill.swift`, into both the CLI package and the app — the same file twice, because the
CLI is a separate SwiftPM package and the app's synchronized folder cannot reach outside it.
`rocuronium guide` prints these files; the app installs them into `~/.claude/skills`.

The generated files are committed. `DocsConsistencyTests` (CLI) and `EmbeddedSkillTests` (app)
compare them against the skill directory, so an edit to the skill without a rerun fails the
build instead of shipping stale text. `Scripts/embed-cli.sh` reruns this before every release.

Usage: Scripts/embed-skill.py [--check]
  --check   exit 1 if either output would change (nothing is written)
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / ".claude" / "skills" / "rocuronium"
OUTPUTS = [
    ROOT / "RocuroniumCLI" / "Sources" / "rocuronium" / "EmbeddedSkill.swift",
    ROOT / "Rocuronium" / "App" / "EmbeddedSkill.swift",
]
OPEN = '##"""'
CLOSE = '"""##'

HEADER = '''// Generated by Scripts/embed-skill.py from .claude/skills/rocuronium — edit the skill and
// rerun the script; edits made here are overwritten.
import Foundation

/// The agent skill, as shipped inside the binary: what `rocuronium guide` prints, and what
/// the app installs into `~/.claude/skills/rocuronium` for a harness that loads skills.
nonisolated enum EmbeddedSkill {
    struct File: Sendable, Hashable {
        /// Relative to the skill directory: `SKILL.md`, `reference/acting.md`, …
        let path: String
        let contents: String
    }

    static let name = "rocuronium"

    /// Where Claude Code looks for user-level skills.
    static var defaultInstallDirectory: URL {
        URL.homeDirectory.appending(path: ".claude").appending(path: "skills").appending(path: name)
    }

    enum InstallState: Equatable, Sendable {
        case notInstalled
        case current
        /// The paths whose installed contents differ from this build, or are missing.
        case outdated([String])
    }

    /// Compares every embedded file with the copy on disk. A directory with none of the
    /// files is not installed; one with any file missing or different is outdated.
    static func state(at directory: URL) -> InstallState {
        var differing: [String] = []
        var present = 0
        for file in files {
            let url = directory.appending(path: file.path)
            guard let installed = try? String(contentsOf: url, encoding: .utf8) else {
                differing.append(file.path)
                continue
            }
            present += 1
            if installed != file.contents { differing.append(file.path) }
        }
        if present == 0 { return .notInstalled }
        return differing.isEmpty ? .current : .outdated(differing)
    }

    /// Writes every embedded file into `directory`, creating it as needed. Files the skill
    /// does not carry are left alone.
    static func install(into directory: URL) throws {
        let manager = FileManager.default
        for file in files {
            let url = directory.appending(path: file.path)
            try manager.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try file.contents.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    /// `SKILL.md` first, then the reference files in the order the skill first mentions
    /// them, each under a rule naming its path.
    static var guideText: String {
        guard let skill = files.first(where: { $0.path == "SKILL.md" }) else { return "" }
        let references = files.filter { $0.path != "SKILL.md" }.sorted { a, b in
            let ia = skill.contents.range(of: a.path)?.lowerBound ?? skill.contents.endIndex
            let ib = skill.contents.range(of: b.path)?.lowerBound ?? skill.contents.endIndex
            return ia == ib ? a.path < b.path : ia < ib
        }
        var text = skill.contents
        for reference in references {
            text += "\\n\\n" + String(repeating: "─", count: 24) + "  " + reference.path + "  " + String(repeating: "─", count: 24) + "\\n\\n"
            text += reference.contents
        }
        return text
    }

    /// The reference file whose name contains `topic` (case-insensitive), or `nil`.
    static func reference(matching topic: String) -> File? {
        let needle = topic.lowercased()
        return files.first { $0.path != "SKILL.md" && $0.path.lowercased().contains(needle) }
    }

    static var referencePaths: [String] {
        files.map(\\.path).filter { $0 != "SKILL.md" }
    }

    static let files: [File] = [
'''

FOOTER = '''    ]
}
'''


def render() -> str:
    parts = [HEADER]
    for path in sorted(SKILL.rglob("*.md")):
        relative = path.relative_to(SKILL).as_posix()
        contents = path.read_text(encoding="utf-8")
        for forbidden in (CLOSE, "\\##("):
            if forbidden in contents:
                sys.exit(f"{relative}: contains {forbidden!r}, which the raw string delimiter cannot carry")
        # A multi-line literal drops the newline before its closing delimiter, so one is
        # added back; the closing delimiter sits at column 0 so no indentation is stripped.
        parts.append(f'        File(path: "{relative}", contents: {OPEN}\n{contents}\n{CLOSE}),\n')
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    if not SKILL.is_dir():
        sys.exit(f"no skill directory at {SKILL}")
    rendered = render()
    check = "--check" in sys.argv[1:]
    stale = [out for out in OUTPUTS if not out.exists() or out.read_text(encoding="utf-8") != rendered]
    if check:
        for out in stale:
            print(f"stale: {out.relative_to(ROOT)}")
        return 1 if stale else 0
    for out in OUTPUTS:
        out.write_text(rendered, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
